project:
  type: website
  output-dir: docs
website:
  title: "Yuean Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Yuean Wang Resume.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



